### ISSUE TITLE
possibilité 2 compteurs

### ISSUE THREAD

**Issue by michael067** [fairecasoimeme/ZiPulses#1]
Bonjour,
Est-il prévu un zipulses double pour collecter par exemple le compteur d'eau chaude et d'eau froide ?

**Comment by fairecasoimeme** [comment]
Bonjour,
Malheureusement, le ZiPulses n'aura qu'une seule entrée impulsion.
Pour gérer 2 compteurs, il faudra 2 ZiPulses
