### ISSUE TITLE
ZiPulses pas reconnu dans Z2M

### ISSUE THREAD

**Issue by mrgnsrl** [fairecasoimeme/ZiPulses#13]
Je n'arrive pas à associer mon ZiPulses dans Z2M, il est reconnu comme non supporté :
<img width="814" alt="image" src="https://github.com/fairecasoimeme/ZiPulses/assets/62310212/b4cdced5-bd08-4a13-a0c5-046842afe5e6">

Z2M est en version 1.31.2-dev :
<img width="608" alt="image" src="https://github.com/fairecasoimeme/ZiPulses/assets/62310212/332dcc35-5248-4aaf-811f-0e9ec28c77f4">

**Comment by Gonioul** [comment]
Entretien terminé = Faux.
-> Il faut recommencer l'appairage.

Je conseille de supprimer l'appareil, redémarrer l'addon zigbee2mqtt et de réessayer.

**Comment by mrgnsrl** [comment]
Merci, j'ai du sélectionner l'équipement le plus proche pour l'appairage sinon l'entretien échouait systématiquement.

Tout fonctionne parfaitement !
