### ISSUE TITLE
Zipulse mort après 2h de fonctionnement

### ISSUE THREAD

**Issue by Snoofy26** [fairecasoimeme/ZiPulses#31]
J'ai mis mon zipulse sur un compteur gazpar après appairage.
Tout fonctionnait nickel mais au bout de 2h plus rien.
Je me disais que c'était un pb de portée mais lorsque je l'ai remis à côté du coordinateur et que j'ai appué sur le boutton d'appairage rien ne s'est passé. La led ne s'est même pas allumée.
J'ai d'abord pensé à la pile mais j'ai pris sa tension au multimètre mais la pile est à 3.2V donc ce n'est pas ça.
Un reset n'a rien fait non plus.
Qu'est ce que je loupe ? Un composant aurait grillé ?

**Comment by fairecasoimeme** [comment]
Avez-vous tenté d'appuyer une dizaine de secondes sur le bouton d'appairage ? le switch est bien positionné sur BAT ?

**Comment by Snoofy26** [comment]
C'est bon, le switch BAT/ REG n'était pas au bout de sa course, en le rouvrant j'ai du le bouger sans faire attention.
Ca refonctionne désolé pour le dérangement
