### ISSUE TITLE
Mise à jour du ZiPulses depuis macOS ?

### ISSUE THREAD

**Issue by MilesTEG1** [fairecasoimeme/ZiPulses#41]
Bonjour @fairecasoimeme 
Est-il possible de faire la MAJ du firmware depuis macOS ?
Avez-vous un lien vers une version macOS du binaire qui permet de flasher ?

Merci d'avance.

**Comment by fairecasoimeme** [comment]
Bonjour,

Désolé mais l'application de flashage n'est compilé que pour Windows. J'ai les sources du constructeur mais je ne peux pas les fournir.

**Comment by MilesTEG1** [comment]
Ha mince...
Et vous n'avez pas de mac, je suppose, pour compiler une version macOS ? 😭

**Comment by MilesTEG1** [comment]
Est-ce que ceci permettrait de flasher depuis macOS ?
https://github.com/dfu-programmer/dfu-programmer

**Comment by fairecasoimeme** [comment]
malheureusement non :( pas de mac.
Non dfu-programmer ne permet pas de flasher car le chip est un NXP JN5189

**Comment by MilesTEG1** [comment]
Bon je vais devoir me résigner à utiliser un pc windows 😓

**Comment by samsam-rolon** [comment]
Bonjour,
Est-ce toujours d'actualité ?
Double peine, j'ai un Mac OS en architecture ARM ...
Samuel

**Comment by MilesTEG1** [comment]
Salut 👋🏻
J'avoue que ce n'est pas pratique de devoir démonter le ZiPulses pour le mettre à jour.
Et surtout il faut un PC windows.
Ou une machine virtuelle, mais je trouve ça un peu "too much" juste pour faire une mise à jour.

@fairecasoimeme Serait-il possible de faire une maj OTA sur le ZiPulses à l'instar du ZLinky ?

**Comment by samsam-rolon** [comment]
J'ai triché, je suis passé via une image docker Ubuntu 22.04 (24.04 ne permet pas d'installer nativement libncurses5 mais libncurses6 ...) sur mon Nas Synology

**Comment by MilesTEG1** [comment]
> J'ai triché, je suis passé via une image docker Ubuntu 22.04 (24.04 ne permet pas d'installer nativement libncurses5 mais libncurses6 ...) sur mon Nas Synology

Haa ! ta procédure m'intéresse ;) Serait-il possible de déployer ce conteneur sur un mac ARM ?

**Comment by fairecasoimeme** [comment]
Tout le problème de l'OTA est lié au fait que le ZiPulses puisse fonctionner sur une pile avec peu d'énergie.
Si je permet l'OTA, je vais me retrouver avec une augmentation du SAV à chaque mise à jour.
Une prochaine version du Zipulses va sortir avec une pile qui double la capacité. je vais donc réfléchir à l'intégrer et faire des tests pour voir si c'est viable. Mais du coup, le firmware ne pourra être compatible qu'avec la nouvelle version.

**Comment by elli0tvr** [comment]
> > J'ai triché, je suis passé via une image docker Ubuntu 22.04 (24.04 ne permet pas d'installer nativement libncurses5 mais libncurses6 ...) sur mon Nas Synology
> 
> Haa ! ta procédure m'intéresse ;) Serait-il possible de déployer ce conteneur sur un mac ARM ?


```bash
➜  x86_64 > docker run -it --rm  -v $(pwd):/app --device /dev/ttyUSB0:/dev/ttyUSB0 --platform linux/amd64 debian:12 bash
root@17397c538a44:/# apt update && apt install -y libusb-1.0-0 libncurses5
root@17397c538a44:/# cd /app/
root@17397c538a44:/app# ./DK6Programmer

NXP DK6 Device Programmer (Build 2282)
...
```
Dans Docker Desktop, pour permettre l'émulation amd64, j'ai mis ça :

<img width="617" height="347" alt="Image" src="https://github.com/user-attachments/assets/9c0d429e-9a79-4449-becd-c533c2cbb0ca" />

Pour la partie /dev/ttyUSB0, faut tester, j'ai pas mon flasher/zipulse sous la main, donc j'ai imaginé.
