### ISSUE TITLE
Pourcentage batterie?

### ISSUE THREAD

**Issue by Gonioul** [fairecasoimeme/ZiPulses#5]
Je sais que le ZiPulses peut être aussi alimenté par autre chose, mais dans le cas où il est alimenté par une pile, il n'y aurait pas moyen d'avoir d'autres informations que la tension?
Zigbee2Mqtt est incapable de donner le pourcentage.

![image](https://user-images.githubusercontent.com/64291573/228945550-ca0444a9-0d8d-400a-9683-ba260b35fedc.png)

![image](https://user-images.githubusercontent.com/64291573/228946491-698ed777-caa8-4ba1-b08f-33799d14e115.png)

**Comment by fairecasoimeme** [comment]
Pour le moment pas de remontée d'un pourcentage, uniquement la tension car compliqué de faire un pourcentage sur une pile lithium mais en plus lorsqu'il peut y avoir plusieurs sources d'alimentation.
Cependant, je le garde comme possible amélioration du firmware

**Comment by Gonioul** [comment]
Et en demandant à Zigbee2Mqtt de faire le calcul, ça serait peut-être plus simple?

**Comment by fairecasoimeme** [comment]
J'ai rajouté le pourcentage de batterie dans la version 3.0.
les données (temperature / voltage / pourcentage) remonte toutes les 2 heures mais aussi 1 minute après premier démarrage
