### ISSUE TITLE
ZiPulses et compteur FlowIQ 2200

### ISSUE THREAD

**Issue by MichaelBitard** [fairecasoimeme/ZiPulses#7]
Bonjour,

J'ai un compteur FlowIQ 2200 (installé par la mairie de Toulouse), je n'arrive pas à trouver dans la documentation si il est à impulsions ILS.

Comment puis-je trouver cette information ?

**Comment by fairecasoimeme** [comment]
Bonjour,
d'après ce que je lis ici : https://www.bimobject.com/fr/kamstrup/product/02-k-xx-d-x-1a-x-xx
la sortie impulsion est une option, si vous n'avez pas de câble qui sort de votre compteur d'eau, peu de chance qu'il y ait l'option.
Je ne sais pas s'il est possible d'acheter le module et comment il fonctionne.

**Comment by MichaelBitard** [comment]
Merci, je vais regarder si je trouve quelque chose de ce côté là !

Je mettrais à jour le ticket si j'y arrive
