### ISSUE TITLE
ZiPulses (BAT) - GAZPAR - Pas de valeur energy

### ISSUE THREAD

**Issue by MrRometo** [fairecasoimeme/ZiPulses#9]
Bonjour,

Je ne comprends pas je suis sur HomeAssistant / Zigbee2MQTT, je viens de recevoir et d'installer le Zipulses mais je n'ai pas toutes les informations qui remontent.

Et la principale (celle qui m'intéresse) je ne l'ai pas --> ENERGY

Pourtant le capteur reçoit bien l'impulsion car la LED s'allume bleu à chaque fois.

![image](https://user-images.githubusercontent.com/74415292/234301537-e2f07db2-beed-4b8d-ab7d-05ac23a12cbe.png)

Si quelqu'un a une idée je suis preneur.

Je suis également le sujet [ici](https://forum.hacf.fr/t/lixee-zipulses/22296/18?u=mrrometo)

**Comment by fairecasoimeme** [comment]
Bonjour,

Le coefficient multiplicateur ne doit pas être à 0 car impulsions x 0 donnera 0

**Comment by fairecasoimeme** [comment]
Après avoir paramétré le multiplicateur, il faut bien faire la manipulation suivante : 
https://github.com/fairecasoimeme/ZiPulses#z2m en vérifiant bien que les deux encarts vert apparaissent.

Il faut aussi vérifier que le ZiPulses s'allume quand vous relier les deux bornes du "pulses" (pour simuler une impulsion). Si ce n'est pas cas, il y a un problème matériel sur le ZiPulses.

**Comment by MrRometo** [comment]
Je ne comprends pourquoi je récupère les informations du capteur (voltage, temperature, linkquality) mais pas celle du compteur à impulsion (energy).

Alors que l'impulsion à l'air d'arriver.

**Comment by MrRometo** [comment]
Bon après 5 ou 6 désappairage réappairage en suivant la doc à chaque fois ça fonctionne ! Je ne touche plus à rien!

![image](https://user-images.githubusercontent.com/74415292/235099666-d9eb345b-7f95-4824-b36f-15054c963113.png)

Merci pour votre aide.
